// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Template is one recurring item and how often it appears.
 */
export interface Template {
    "id": string;
    "text": string;
    "cadence": string;
}
