// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Hit is a search result.
 */
export interface Hit {
    "path": string;
    "snippet": string;
}

/**
 * Label is a label and how many places it appears.
 */
export interface Label {
    "name": string;
    "count": number;
}

/**
 * Workplan summarises a dated daily note.
 */
export interface Workplan {
    "path": string;
    "date": string;
    "hours": string;
    "minutes": number;
    "dayType": string;
    "open": number;
    "done": number;
}
