// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Item is one action item.
 */
export interface Item {
    /**
     * Text is the visible text, including any #labels and [hh:mm] token. It is
     * stored exactly as written so serialising cannot reorder or drop anything.
     */
    "Text": string;
    "Done": boolean;

    /**
     * Depth is the nesting level; 0 is top level.
     */
    "Depth": number;

    /**
     * Body holds the item's own markdown lines with the common indent removed.
     */
    "Body": string[] | null;

    /**
     * stable across rollover
     */
    "ID": string;

    /**
     * "hh:mm" — when the item was added
     */
    "CreatedAt": string;

    /**
     * "hh:mm" — when it was ticked
     */
    "DoneAt": string;

    /**
     * "yyyy-mm-dd" the item was first created, once carried
     */
    "From": string;

    /**
     * how many days it has rolled over
     */
    "Carried": number;

    /**
     * id of the recurring template that seeded it
     */
    "Recurring": string;
}
