// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes application-level state to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetInfo returns the current application info.
 */
export function GetInfo(): $CancellablePromise<$models.Info> {
    return $Call.ByID(1573130285);
}

/**
 * GetSettings returns the active settings.
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(499889888);
}

/**
 * SaveSettings persists new settings and adopts them for this session.
 */
export function SaveSettings(s: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(354768091, s);
}
