// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes application-level state to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetInfo returns the current application info.
 */
export function GetInfo(): $CancellablePromise<$models.Info> {
    return $Call.ByID(1573130285);
}

/**
 * GetSettings returns the active settings.
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(499889888);
}

/**
 * SaveSettings persists new settings. Changing the vault path takes effect on
 * the next launch rather than mid-session, since the open vault, index and
 * watcher are all bound to the current one.
 */
export function SaveSettings(s: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(354768091, s);
}

/**
 * SaveWindow remembers the window's bounds so the next launch reopens the same
 * way. Called from the window event hooks in main, not from the frontend.
 */
export function SaveWindow(w: config$0.Window): $CancellablePromise<void> {
    return $Call.ByID(2092487314, w);
}

/**
 * SetFonts persists the chosen typography. Unknown ids fall back to the defaults
 * on the next load, so a stale value can never leave the interface fontless.
 */
export function SetFonts(f: config$0.Fonts): $CancellablePromise<void> {
    return $Call.ByID(1349400413, f);
}

/**
 * SetSplit records how the items and notes sections sit together. It is a
 * display choice like the theme, so it lives beside it rather than in the note.
 */
export function SetSplit(split: string): $CancellablePromise<void> {
    return $Call.ByID(3828383287, split);
}

/**
 * SetTheme persists the theme choice: system, light or dark.
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(3261068070, theme);
}
