// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AttachmentService stores images pasted into a note.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Save writes a pasted image into the vault and returns the path to put in the
 * markdown. The path is relative to the vault root — "attachments/x.png" — so
 * the same link resolves in the app, in another markdown editor, and in the
 * file tree itself.
 * 
 * The image arrives base64-encoded because that is what crosses the bindings;
 * it is decoded here and written as bytes.
 */
export function Save(ext: string, data: string): $CancellablePromise<string> {
    return $Call.ByID(3918632298, ext, data);
}
