// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BackupService exports the vault to a bundle and restores it again.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * DefaultBundleName is the filename suggested in the save dialog.
 */
export function DefaultBundleName(): $CancellablePromise<string> {
    return $Call.ByID(3191575482);
}

/**
 * Export writes the whole vault to a zip at dir, returning the bundle path.
 * The index is left out; it is rebuilt from the notes on the next launch.
 */
export function Export(dir: string): $CancellablePromise<string> {
    return $Call.ByID(1983393474, dir);
}

/**
 * Restore extracts a bundle over the vault and rebuilds the index from what
 * lands on disk, so the cache can never disagree with the restored notes.
 */
export function Restore(bundle: string): $CancellablePromise<void> {
    return $Call.ByID(2870622, bundle);
}
