// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HoursSummary is the time worked over a date range.
 */
export interface HoursSummary {
    "from": string;
    "to": string;
    "minutes": number;
    "hours": string;
}

/**
 * Info is the snapshot the frontend needs on startup.
 */
export interface Info {
    "version": string;
    "vaultPath": string;
    "workplanDir": string;
    "theme": string;
    "repository": string;
    "website": string;
    "releases": string;
    "licence": string;
}

/**
 * ItemInput is an action item as the editor holds it: only the fields a person
 * can change. Timestamps, carry counters and recurring ids are metadata the
 * editor never sees, and are preserved by id on save.
 */
export interface ItemInput {
    "id": string;
    "text": string;
    "done": boolean;
    "depth": number;
    "body": string[] | null;
}

/**
 * Note is a note as the editor needs it: its frontmatter, its items, and the
 * free-form markdown below them.
 */
export interface Note {
    "path": string;
    "id": string;
    "type": string;
    "date": string;
    "hours": string;
    "dayType": string;
    "layout": string;
    "labels": string[] | null;
    "items": NoteItem[] | null;
    "body": string;
    "title": string;
}

/**
 * NoteItem is one action item, flattened for the editor.
 */
export interface NoteItem {
    "id": string;
    "text": string;
    "done": boolean;
    "depth": number;
    "minutes": number;
    "labels": string[] | null;
    "createdAt": string;
    "doneAt": string;
    "from": string;
    "carried": number;
    "recurring": string;
    "body": string[] | null;
}
