// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info is the snapshot the frontend needs on startup.
 */
export interface Info {
    "version": string;
    "vaultPath": string;
    "workplanDir": string;
}
