// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";

/**
 * HoursSummary is the time worked over a date range.
 */
export interface HoursSummary {
    "from": string;
    "to": string;
    "minutes": number;
    "hours": string;
}

/**
 * Info is the snapshot the frontend needs on startup.
 */
export interface Info {
    "version": string;
    "vaultPath": string;
    "workplanDir": string;
    "theme": string;
    "fonts": config$0.Fonts;
    "repository": string;
    "website": string;
    "releases": string;
    "licence": string;

    /**
     * UpdateCheck is "ask" until the user has answered whether the app may
     * look for new releases, then "auto" or "never".
     */
    "updateCheck": string;

    /**
     * Split is how items and notes sit together; see config.Settings.
     */
    "split": string;
}

/**
 * ItemInput is an action item as the editor holds it: only the fields a person
 * can change. Timestamps, carry counters and recurring ids are metadata the
 * editor never sees, and are preserved by id on save.
 */
export interface ItemInput {
    "kind": string;
    "level": number;
    "id": string;
    "text": string;
    "done": boolean;
    "depth": number;
    "body": string[] | null;
}

/**
 * Note is a note as the editor needs it: its frontmatter, its items, and the
 * free-form markdown below them.
 */
export interface Note {
    "path": string;
    "id": string;
    "type": string;
    "date": string;
    "hours": string;
    "dayType": string;
    "layout": string;
    "labels": string[] | null;
    "items": NoteItem[] | null;
    "body": string;
    "title": string;
}

/**
 * NoteItem is one action item or group heading, flattened for the editor.
 */
export interface NoteItem {
    "kind": string;
    "level": number;
    "id": string;
    "text": string;
    "done": boolean;
    "depth": number;
    "minutes": number;
    "labels": string[] | null;
    "createdAt": string;
    "doneAt": string;
    "from": string;
    "carried": number;
    "recurring": string;
    "body": string[] | null;
}

/**
 * UpdateState is everything the frontend needs to render the update banner.
 */
export interface UpdateState {
    "phase": string;

    /**
     * Version is the newer release, when there is one.
     */
    "version": string;

    /**
     * Percent is download progress, 0 unless downloading.
     */
    "percent": number;

    /**
     * Message explains a failure; empty otherwise.
     */
    "message": string;

    /**
     * CanInstall is false when the binary is not ours to replace — a
     * package-managed or read-only install — and the UI offers the release
     * page instead.
     */
    "canInstall": boolean;

    /**
     * ReleaseURL is the page for the newer release.
     */
    "releaseUrl": string;
}
