// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NotesService is the frontend's access to the vault tree and note contents.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vault$0 from "../internal/vault/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create makes a new empty note and returns its path. If the path is taken the
 * name gets a numeric suffix — "Untitled 2" — rather than overwriting a note the
 * user cannot see.
 */
export function Create(path: string): $CancellablePromise<string> {
    return $Call.ByID(2629606293, path);
}

/**
 * CreateFolder makes a folder, including any missing parents.
 */
export function CreateFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(4242346733, path);
}

/**
 * Delete removes a note, or a folder and everything under it.
 */
export function Delete(path: string): $CancellablePromise<void> {
    return $Call.ByID(204237970, path);
}

/**
 * DeleteForever removes one trash entry permanently.
 */
export function DeleteForever(id: string): $CancellablePromise<void> {
    return $Call.ByID(1781375193, id);
}

/**
 * EmptyTrash removes every trash entry permanently.
 */
export function EmptyTrash(): $CancellablePromise<void> {
    return $Call.ByID(640602140);
}

/**
 * Get reads one note.
 */
export function Get(path: string): $CancellablePromise<$models.Note | null> {
    return $Call.ByID(1939223039, path);
}

/**
 * GetRaw returns a note's markdown for the raw editor.
 */
export function GetRaw(path: string): $CancellablePromise<string> {
    return $Call.ByID(4124668463, path);
}

/**
 * ListTrash returns the recoverable deleted notes and folders, newest first.
 */
export function ListTrash(): $CancellablePromise<vault$0.TrashEntry[] | null> {
    return $Call.ByID(2068799449);
}

/**
 * Reindex rebuilds the index from the notes on disk. It backs the file watcher
 * and the "something changed underneath us" recovery path.
 */
export function Reindex(): $CancellablePromise<void> {
    return $Call.ByID(1435180516);
}

/**
 * Rename moves a note or folder.
 */
export function Rename($from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(300488011, $from, to);
}

/**
 * Restore brings a trashed note or folder back and returns where it landed.
 */
export function Restore(id: string): $CancellablePromise<string> {
    return $Call.ByID(62200425, id);
}

/**
 * SaveBody replaces the free-form markdown below the items and nothing else:
 * the frontmatter and every item line are written back exactly as they were.
 * An empty body removes the section rather than leaving a blank stub.
 */
export function SaveBody(path: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(1514606156, path, body);
}

/**
 * SaveRaw replaces a note's markdown wholesale, which is what the raw editor does.
 */
export function SaveRaw(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3320378662, path, content);
}

/**
 * SetLabels replaces a note's own labels (the frontmatter ones, as opposed to
 * the #labels on individual items).
 */
export function SetLabels(path: string, labels: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(886785392, path, labels);
}

/**
 * SetLayout chooses which sections a note shows. Workplans are always items
 * then notes, so they refuse a layout rather than silently ignoring it.
 */
export function SetLayout(path: string, layout: string): $CancellablePromise<void> {
    return $Call.ByID(3780901249, path, layout);
}

/**
 * Tree returns the folder and note tree for the sidebar.
 */
export function Tree(): $CancellablePromise<vault$0.Node | null> {
    return $Call.ByID(4183907693);
}
