// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService answers the label and full-text queries the index exists for.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as index$0 from "../internal/index/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * HoursBetween totals the hours worked over an inclusive date range. Because
 * hours are one field per note, this is a single query rather than a tree scan.
 */
export function HoursBetween($from: string, to: string): $CancellablePromise<$models.HoursSummary> {
    return $Call.ByID(3192845851, $from, to);
}

/**
 * HoursThisWeek totals the current week, Monday to Sunday.
 */
export function HoursThisWeek(): $CancellablePromise<$models.HoursSummary> {
    return $Call.ByID(1807776997);
}

/**
 * Labels returns every label with how many places it is used.
 */
export function Labels(): $CancellablePromise<index$0.Label[] | null> {
    return $Call.ByID(3766572161);
}

/**
 * NotesByLabel returns the notes carrying a label.
 */
export function NotesByLabel(name: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(830297144, name);
}

/**
 * Search runs a full-text query over note contents.
 */
export function Search(query: string): $CancellablePromise<index$0.Hit[] | null> {
    return $Call.ByID(1591404538, query);
}
