// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService checks for new releases and installs them.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check asks GitHub for the latest release.
 * 
 * It never returns an error. A background check that fails goes quiet — an
 * updater that complains every time the wifi is down is worse than none — while
 * a check the user pressed reports what went wrong.
 */
export function Check(manual: boolean): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(1550391149, manual);
}

/**
 * Install downloads the newest release and puts it in place. The running
 * process keeps working on the old binary until it is restarted.
 */
export function Install(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(426444410);
}

/**
 * Scheduled is the check the app runs on its own. It makes no request at all
 * unless the user has agreed to automatic checks — this is the single gate on
 * the only outbound traffic Nota has, which is why it lives here under test
 * rather than inline in the scheduler.
 */
export function Scheduled(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(1208975762);
}

/**
 * SetPreference records whether the app may check for updates. This is the only
 * switch on any outbound network traffic the app makes.
 */
export function SetPreference(check: string): $CancellablePromise<void> {
    return $Call.ByID(3028307392, check);
}

/**
 * State returns the current update state without checking anything.
 */
export function State(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(1170995836);
}
