// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkplanService is the frontend's access to the dated daily notes and to
 * editing action items.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as index$0 from "../internal/index/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workplan$0 from "../internal/workplan/models.js";

/**
 * AddItem appends an action item to a note and returns its new id.
 */
export function AddItem(path: string, text: string, depth: number): $CancellablePromise<string> {
    return $Call.ByID(3519571340, path, text, depth);
}

/**
 * AddItemMinutes adds to the time logged against an item.
 */
export function AddItemMinutes(path: string, id: string, minutes: number): $CancellablePromise<void> {
    return $Call.ByID(207789805, path, id, minutes);
}

/**
 * EnsureToday creates today's workplan if it is missing, rolling unfinished
 * items forward, and returns its path. An empty path means today is a weekend
 * and weekend notes are switched off.
 */
export function EnsureToday(): $CancellablePromise<string> {
    return $Call.ByID(1753420751);
}

/**
 * List returns the workplans newest first, for the sidebar.
 */
export function List(): $CancellablePromise<index$0.Workplan[] | null> {
    return $Call.ByID(1079518592);
}

/**
 * RemoveItem deletes an item and anything nested beneath it.
 */
export function RemoveItem(path: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(2797701871, path, id);
}

/**
 * SaveTemplates replaces the recurring items file with the given lines.
 */
export function SaveTemplates(content: string): $CancellablePromise<void> {
    return $Call.ByID(1800721784, content);
}

/**
 * SetDayType marks a day work, weekend, leave or holiday.
 */
export function SetDayType(path: string, dayType: string): $CancellablePromise<void> {
    return $Call.ByID(2642876146, path, dayType);
}

/**
 * SetHours records the hours worked on a day, in hh:mm.
 */
export function SetHours(path: string, hours: string): $CancellablePromise<void> {
    return $Call.ByID(4153139527, path, hours);
}

/**
 * SetItemBody replaces the free-form markdown under an item, which is where
 * code, JSON and prose belonging to that item live.
 */
export function SetItemBody(path: string, id: string, body: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3636351647, path, id, body);
}

/**
 * SetItemDone ticks or unticks an item, stamping the completion time.
 */
export function SetItemDone(path: string, id: string, done: boolean): $CancellablePromise<void> {
    return $Call.ByID(2643528627, path, id, done);
}

/**
 * SetItemText replaces an item's visible text, labels and time token included.
 */
export function SetItemText(path: string, id: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1345914944, path, id, text);
}

/**
 * SuggestedMinutes totals the time logged against a day's items. It pre-fills
 * the hours field and is never written in automatically, since much of a working
 * day never lands on an action item.
 */
export function SuggestedMinutes(path: string): $CancellablePromise<number> {
    return $Call.ByID(3772892904, path);
}

/**
 * Templates returns the configured recurring items.
 */
export function Templates(): $CancellablePromise<workplan$0.Template[] | null> {
    return $Call.ByID(1926328227);
}
