// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkplanService is the frontend's access to the dated daily notes and to
 * saving a note's action items.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as index$0 from "../internal/index/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mdnote$0 from "../internal/mdnote/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workplan$0 from "../internal/workplan/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EnsureToday creates today's workplan if it is missing, rolling unfinished
 * items forward, and returns its path. An empty path means today is a weekend
 * and weekend notes are switched off.
 */
export function EnsureToday(): $CancellablePromise<string> {
    return $Call.ByID(1753420751);
}

/**
 * List returns the workplans newest first, for the sidebar.
 */
export function List(): $CancellablePromise<index$0.Workplan[] | null> {
    return $Call.ByID(1079518592);
}

/**
 * SaveItems replaces a note's action items in one write. This is the only way
 * the editor changes items: it edits a local copy and sends the whole list, so
 * keyboard navigation and multi-line paste never wait on a round trip. Items
 * with no id are new and get one minted here, stamped with the current time.
 */
export function SaveItems(path: string, items: $models.ItemInput[] | null): $CancellablePromise<mdnote$0.Item[] | null> {
    return $Call.ByID(2739606815, path, items);
}

/**
 * SaveTemplates replaces the recurring items file with the given lines.
 */
export function SaveTemplates(content: string): $CancellablePromise<void> {
    return $Call.ByID(1800721784, content);
}

/**
 * SetDayType marks a day work, weekend, leave or holiday.
 */
export function SetDayType(path: string, dayType: string): $CancellablePromise<void> {
    return $Call.ByID(2642876146, path, dayType);
}

/**
 * SetHours records the hours worked on a day, in hh:mm.
 */
export function SetHours(path: string, hours: string): $CancellablePromise<void> {
    return $Call.ByID(4153139527, path, hours);
}

/**
 * Templates returns the configured recurring items.
 */
export function Templates(): $CancellablePromise<workplan$0.Template[] | null> {
    return $Call.ByID(1926328227);
}
