// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the user's configuration, persisted as .nota/settings.json.
 */
export interface Settings {
    /**
     * VaultPath is the root directory of the markdown vault, always absolute.
     */
    "vaultPath": string;

    /**
     * WorkplanFolder is the vault-relative folder holding the dated daily notes.
     */
    "workplanFolder": string;

    /**
     * CreateOnWeekends controls whether a workplan is created on Saturday and
     * Sunday. Rollover copes with gaps either way; this only decides whether a
     * weekend gets a note at all.
     */
    "createOnWeekends": boolean;
}
