// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Fonts are the faces the interface, the notes area and code use, by id, plus a
 * size step. The ids name faces bundled with the application (see the frontend
 * catalogue), or "system" for the platform default.
 */
export interface Fonts {
    "ui": string;
    "notes": string;
    "code": string;
    "size": string;
}

/**
 * Settings is the user's configuration, persisted as .nota/settings.json.
 */
export interface Settings {
    /**
     * VaultPath is the root directory of the markdown vault, always absolute.
     */
    "vaultPath": string;

    /**
     * WorkplanFolder is the vault-relative folder holding the dated daily notes.
     */
    "workplanFolder": string;

    /**
     * CreateOnWeekends controls whether a workplan is created on Saturday and
     * Sunday. Rollover copes with gaps either way; this only decides whether a
     * weekend gets a note at all.
     */
    "createOnWeekends": boolean;

    /**
     * Theme is "system", "light" or "dark".
     */
    "theme": string;

    /**
     * Window remembers where the window was left; see Window.Valid.
     */
    "window": Window;

    /**
     * Fonts is the chosen typography; see Fonts.
     */
    "fonts": Fonts;

    /**
     * Updates controls the release check; see Updates.
     */
    "updates": Updates;

    /**
     * Split is how the items and notes sections sit together on a page that
     * shows both: "rows" stacks them, "columns" puts them side by side.
     */
    "split": string;
}

/**
 * Updates controls whether the app looks for new releases. Nota makes no
 * network requests of any other kind, so this single field is the whole of its
 * outbound traffic — which is why it starts at "ask" rather than at a default
 * somebody has to discover and turn off.
 */
export interface Updates {
    /**
     * Check is "ask" until the user answers, then "auto" or "never".
     */
    "check": string;

    /**
     * LastCheck is when the last successful check ran, RFC 3339, so relaunching
     * repeatedly does not re-ask GitHub each time. Empty until the first one.
     */
    "lastCheck"?: string;
}

/**
 * Window is the last size and position the user left the window at, so it can
 * reopen the same way. The zero value means "never saved", which is how a first
 * launch is told apart from a remembered one.
 */
export interface Window {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximised": boolean;
}
