// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Node is one entry in the folder tree.
 */
export interface Node {
    /**
     * Name is the display name: a folder's directory name, or a note's filename
     * without the .md extension.
     */
    "name": string;

    /**
     * Path is the vault-relative path, always with forward slashes.
     */
    "path": string;
    "isFolder": boolean;
    "children"?: (Node | null)[] | null;
}

/**
 * TrashEntry is one deleted note or folder, recoverable until purged.
 */
export interface TrashEntry {
    /**
     * ID is the entry's directory name under .nota/trash.
     */
    "id": string;

    /**
     * Path is where the note or folder lived, vault-relative.
     */
    "path": string;
    "name": string;
    "isFolder": boolean;
    "deletedAt": string;
}
